# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(help_text='My Website', max_length=100),
        ),
    ]
